import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, Cloud, CloudRain, CloudSun, Lightbulb, Sun, ThermometerSun } from "lucide-react";
import { PageShell } from "@/components/navigation";
import { Footer, SectionHeader } from "@/components/shared";
import { RecipeCard } from "@/components/recipe-card";
import { recipes } from "@/data/recipes";

export const metadata: Metadata = {
  title: "Umpan Ikan Mas Berdasarkan Cuaca",
  description: "Pilih racikan umpan ikan mas berdasarkan musim hujan, musim panas, cuaca mendung, atau cerah.",
};

const guides = [
  { id: "musim-hujan", title: "Musim Hujan", emoji: "🌧️", icon: CloudRain, description: "Perubahan suhu dan aliran air bisa memengaruhi aktivitas ikan. Racikan beraroma gurih sering menjadi titik awal yang dicoba pemancing.", conditions: ["Hujan ringan hingga sedang", "Air dapat berubah lebih keruh", "Perhatikan aliran masuk kolam"], tip: "Sesuaikan kelembapan adonan agar tetap menempel saat air lebih aktif. Hindari menambahkan essen terlalu banyak sekaligus.", filter: (recipe: (typeof recipes)[number]) => recipe.seasons.includes("Musim Hujan") },
  { id: "musim-panas", title: "Musim Panas", emoji: "☀️", icon: Sun, description: "Pada hari panas, suhu permukaan dan kejernihan air dapat berubah. Racikan dengan aroma lebih ringan bisa menjadi opsi awal.", conditions: ["Cuaca panas atau cerah", "Ikan mungkin mencari area teduh", "Air kolam bisa lebih hangat"], tip: "Coba cari spot teduh dan mulai dengan aroma yang ringan. Respons tiap kolam berbeda, jadi uji dengan takaran kecil.", filter: (recipe: (typeof recipes)[number]) => recipe.seasons.includes("Musim Panas") || recipe.seasons.includes("Kemarau") },
  { id: "mendung", title: "Mendung", emoji: "☁️", icon: Cloud, description: "Cuaca teduh sering memberi transisi yang menarik antara panas dan hujan. Racikan fleksibel membantu saat kondisi sulit ditebak.", conditions: ["Cahaya matahari tidak langsung", "Cuaca bisa berubah cepat", "Pantau kejernihan air"], tip: "Bawa satu racikan utama dan satu alternatif dengan aroma berbeda. Catat pergantian cuaca saat ikan mulai merespons.", filter: (recipe: (typeof recipes)[number]) => recipe.weather.includes("Mendung") },
  { id: "cerah", title: "Cerah", emoji: "🌤️", icon: CloudSun, description: "Visibilitas air dapat lebih baik saat cerah. Banyak pemancing memulai dari racikan natural dan mengamati respons ikan.", conditions: ["Cahaya cukup terang", "Air dapat terlihat lebih jernih", "Perhatikan bayangan di spot"], tip: "Mulai dengan umpan beraroma ringan dan hindari gerakan berlebihan di tepi kolam yang tenang.", filter: (recipe: (typeof recipes)[number]) => recipe.weather.includes("Cerah") || recipe.weather.includes("Berawan") },
];

export default function WeatherPage() {
  return (
    <PageShell>
      <main className="mx-auto max-w-7xl px-5 pb-16 pt-10 sm:px-8 sm:pt-14">
        <div className="mb-9 grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-[#788878]">Membaca kondisi sebelum melempar kail</p><h1 className="text-4xl font-black tracking-[-.045em] text-[#203326] sm:text-5xl">Umpan & Cuaca</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#748073] sm:text-base">Cuaca memberi konteks, bukan kepastian. Pilih kondisi yang paling dekat dengan sesi mancingmu dan temukan racikan yang pernah dicoba komunitas.</p></div><Link href="/ai-umpan" className="inline-flex min-h-11 items-center gap-2 self-start rounded-xl bg-[#294b34] px-5 text-sm font-bold text-white transition hover:bg-[#203d29] lg:self-auto">Sesuaikan rekomendasi <ArrowRight size={15} /></Link></div>
        <nav aria-label="Pilih kondisi cuaca" className="sticky top-[68px] z-30 mb-10 flex gap-2 overflow-x-auto rounded-2xl border border-[#e6eae3] bg-[#fbfcf9]/95 p-2 backdrop-blur-lg">{guides.map(({ id, title, emoji }) => <a key={id} href={`#${id}`} className="min-h-10 shrink-0 rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-[#526353] shadow-sm transition hover:bg-[#edf3e9]">{emoji} {title}</a>)}</nav>
        <div className="space-y-12">{guides.map((guide, index) => {
          const matchingRecipes = recipes.filter(guide.filter).sort((a, b) => b.users - a.users).slice(0, 3);
          const Icon = guide.icon;
          return <section key={guide.id} id={guide.id} className="scroll-mt-28"><div className="mb-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr] lg:items-stretch"><div className="rounded-[24px] border border-[#e4e9e1] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#edf2e9] text-[#577259]"><Icon size={23} /></span><span className="text-3xl" aria-hidden="true">{guide.emoji}</span></div><h2 className="mt-5 text-2xl font-black tracking-tight text-[#293b2d]">{guide.title}</h2><p className="mt-2 text-sm leading-6 text-[#748073]">{guide.description}</p><ul className="mt-5 grid gap-2">{guide.conditions.map((condition) => <li key={condition} className="flex items-start gap-2 text-xs text-[#647164]"><span className="mt-1 h-1.5 w-1.5 rounded-full bg-[#789173]" />{condition}</li>)}</ul></div><div className="flex flex-col justify-between rounded-[24px] bg-[#203e2c] p-5 text-white sm:p-6"><div><span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.13em] text-[#dfcf9d]"><Lightbulb size={15} /> Tips memancing</span><p className="mt-4 max-w-xl text-base leading-7 text-white/85">{guide.tip}</p></div><div className="mt-6 flex items-end justify-between gap-3 border-t border-white/15 pt-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-white/55">Racikan terkait</p><p className="mt-1 text-lg font-extrabold">{matchingRecipes.length ? matchingRecipes[0].name : "Jelajahi semua"}</p></div><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs text-white/70">{matchingRecipes.length ? `${matchingRecipes.length} rekomendasi` : "Katalog terbuka"}</span></div></div></div><SectionHeader eyebrow={`${index + 1} · Racikan cuaca`} title={`Pilihan untuk ${guide.title.toLowerCase()}`} subtitle="Pengalaman pemancing menjadi panduan, tetapi hasil dan kondisi tiap kolam tetap bervariasi." action={<Link href="/katalog" className="inline-flex items-center gap-1.5 text-sm font-bold text-[#355a3b]">Lihat katalog <ArrowRight size={15} /></Link>} />{matchingRecipes.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{matchingRecipes.map((recipe, recipeIndex) => <RecipeCard key={recipe.slug} recipe={recipe} featured={recipeIndex === 0} />)}</div> : <div className="rounded-2xl border border-dashed border-[#dce4d9] bg-white p-8 text-center text-sm text-[#788478]">Belum ada racikan khusus untuk kondisi ini. Coba gunakan AI Umpan dengan detail spotmu.</div>}</section>;
        })}</div>
        <div className="mt-14 rounded-[24px] border border-[#e7eae4] bg-[#f6f8f4] p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e8eee4] text-[#637a62]"><ThermometerSun size={19} /></span><div><h2 className="font-extrabold text-[#344638]">Perhatikan kondisi di spotmu</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#758074]">Perubahan suhu, kedalaman, sirkulasi, dan kebiasaan ikan berbeda di setiap kolam. Data cuaca di halaman ini adalah panduan umum—bukan prakiraan cuaca real-time atau jaminan hasil tangkapan.</p></div></div><a href="#musim-hujan" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#426445]">Kembali ke atas <ArrowDown size={14} className="rotate-180" /></a></div>
      </main>
      <Footer />
    </PageShell>
  );
}
